#!/usr/bin/env python3
"""build.py — 从 data/templates.json 生成/校验派生文件（单一事实源 SSOT）

用法：
  python3 tools/build.py          # 重新生成所有派生内容（就地修改）
  python3 tools/build.py --check  # 只校验是否同步，不同步则退出码 1（供 CI/提交前检查）

派生内容：
  1. index.html 中 `// === TEMPLATE DATA ... ===` 与 `// === END TEMPLATE DATA ===` 之间的 const TEMPLATES
  2. README.md 中 <!-- QUICKREF:BEGIN --> 与 <!-- QUICKREF:END --> 之间的速查表
  3. skill/SKILL.md 中 <!-- MATRIX:BEGIN --> 与 <!-- MATRIX:END --> 之间的风格标签矩阵
  4. 根目录 NN-*.md 各文件「## 7. Full Prompt Template」围栏代码块（与 JSON prompt 保持一致）
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "templates.json"

BEGIN_MARK = "// === TEMPLATE DATA (GENERATED by tools/build.py from data/templates.json — do not edit by hand) ==="
END_MARK = "// === END TEMPLATE DATA ==="
README_BEGIN = "<!-- QUICKREF:BEGIN -->"
README_END = "<!-- QUICKREF:END -->"
MATRIX_BEGIN = "<!-- MATRIX:BEGIN -->"
MATRIX_END = "<!-- MATRIX:END -->"

CATEGORY_CN = {
    "modern": "现代极简", "retro": "复古经典", "guofeng": "国风中式",
    "euro": "欧式潮流", "texture": "肌理氛围", "business": "商务氛围",
    "experimental": "实验前卫",
}
TEMP_CN = {"warm": "暖调", "cool": "冷调", "neutral": "中性"}
SAT_CN = {"high": "高饱和", "mid": "中饱和", "low": "低饱和", "gray": "灰调"}
VISUAL_CN = {"illustration": "插画", "photo": "摄影", "3d": "3D", "geometric": "几何", "ink": "水墨", "collage": "拼贴"}
SCENE_CN = {"solar": "节气", "business": "商务", "festival": "节日", "daily": "日常", "tech": "科技", "culture": "文化"}


def load_templates():
    templates = json.loads(DATA.read_text(encoding="utf-8"))
    ids = [t["id"] for t in templates]
    assert len(ids) == len(set(ids)), "模板 id 重复"
    for t in templates:
        for field in ("id", "num", "nameCn", "nameEn", "category", "tags", "descType", "examples", "seasons", "prompt"):
            assert field in t, f"{t.get('id')} 缺少字段 {field}"
        assert t["tags"].get("visualType"), f"{t['id']} 缺少 visualType 标签"
        assert len(t["examples"]) >= 1, f"{t['id']} 缺少风格示例"
        assert "`" not in t["prompt"] and "${" not in t["prompt"], f"{t['id']} prompt 含反引号或 ${{}}"
    return templates


def js_str(s):
    """JS 单引号字符串字面量"""
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def gen_templates_js(templates):
    """生成 const TEMPLATES = [...] 的 JS 源码"""
    out = ["const TEMPLATES = ["]
    for t in templates:
        tags = t["tags"]
        scene = ",".join(js_str(s) for s in tags["scene"])
        lines = [
            "  {",
            f"    id: {js_str(t['id'])},",
            f"    num: {js_str(t['num'])},",
            f"    nameCn: {js_str(t['nameCn'])},",
            f"    nameEn: {js_str(t['nameEn'])},",
            f"    desc: {js_str(t['desc'])},",
            f"    visual: {js_str(t['visual'])},",
            f"    category: {js_str(t['category'])},",
            f"    tags: {{ temp: {js_str(tags['temp'])}, sat: {js_str(tags['sat'])}, visualType: {js_str(tags['visualType'])}, scene: [{scene}] }},",
            f"    descType: {js_str(t['descType'])},",
            "    examples: [",
        ]
        for ex in t["examples"]:
            lines.append(f"      {js_str(ex)},")
        lines.append("    ],")
        lines.append("    seasons: {")
        for season, kv in t["seasons"].items():
            pairs = ", ".join(f"{k}: {js_str(v)}" for k, v in kv.items())
            lines.append(f"      {season}: {{ {pairs} }},")
        lines.append("    },")
        if t.get("defaultVariantName"):
            lines.append(f"    defaultVariantName: {js_str(t['defaultVariantName'])},")
        if t.get("variants"):
            lines.append("    variants: [")
            for v in t["variants"]:
                lines.append("      {")
                lines.append(f"        id: {js_str(v['id'])}, nameCn: {js_str(v['nameCn'])}, nameEn: {js_str(v['nameEn'])},")
                lines.append(f"        override: {js_str(v['override'])}")
                lines.append("      },")
            lines.append("    ],")
        lines.append(f"    prompt: `{t['prompt']}`")
        lines.append("  },")
        out.extend(lines)
    out.append("];")
    return "\n".join(out)


def replace_region(text, begin, end, new_body):
    i = text.index(begin)
    j = text.index(end, i)
    return text[: i + len(begin)] + "\n" + new_body + "\n" + text[j:]


def gen_index_region(templates):
    return gen_templates_js(templates)


def gen_readme_table(templates):
    rows = [
        "| # | File | Style (EN) | Style (CN) | Category | Core Visual |",
        "|---|------|-----------|------------|----------|-------------|",
    ]
    for t in templates:
        f = f"{t['num']}-{t['id']}.md"
        cat = CATEGORY_CN[t["category"]]
        rows.append(f"| {t['num']} | [{f}](./{f}) | {t['nameEn']} | {t['nameCn']} | {cat} | {t['desc']} |")
    return "\n".join(rows)


def gen_skill_matrix(templates):
    """生成 SKILL.md 的四维标签矩阵"""
    def names(ts):
        return " / ".join(f"{t['num']} {t['nameCn']}" for t in ts)

    lines = ["用户可通过四维标签快速筛选所需风格：", "", "### 按色温筛选", "", "| 色温 | 匹配模板 |", "|------|---------|"]
    for key in ("warm", "cool", "neutral"):
        ts = [t for t in templates if t["tags"]["temp"] == key]
        lines.append(f"| {TEMP_CN[key]} | {names(ts)} |")
    lines += ["", "### 按饱和度筛选", "", "| 饱和度 | 匹配模板 |", "|--------|---------|"]
    for key in ("high", "mid", "low", "gray"):
        ts = [t for t in templates if t["tags"]["sat"] == key]
        lines.append(f"| {SAT_CN[key]} | {names(ts)} |")
    lines += ["", "### 按视觉类型筛选", "", "| 视觉类型 | 匹配模板 |", "|---------|---------|"]
    for key in ("illustration", "photo", "3d", "geometric", "ink", "collage"):
        ts = [t for t in templates if t["tags"]["visualType"] == key]
        lines.append(f"| {VISUAL_CN[key]} | {names(ts)} |")
    lines += ["", "### 按适用场景筛选", "", "| 场景 | 推荐模板 |", "|------|---------|"]
    for key in ("solar", "business", "festival", "daily", "tech", "culture"):
        ts = [t for t in templates if key in t["tags"]["scene"]]
        lines.append(f"| {SCENE_CN[key]} | {names(ts)} |")
    return "\n".join(lines)


def sync_root_md(templates, check_only, failures):
    """同步根目录 NN-*.md 的 Section 7 prompt 代码块"""
    for t in templates:
        path = ROOT / f"{t['num']}-{t['id']}.md"
        if not path.exists():
            failures.append(f"根目录缺少模板文件 {path.name}")
            continue
        text = path.read_text(encoding="utf-8")
        pattern = re.compile(r"(## 7\. Full Prompt Template[^\n]*\n+```\n?)(.*?)(\n?```)", re.S)
        m = pattern.search(text)
        if not m:
            failures.append(f"{path.name} 未找到 Section 7 代码块")
            continue
        if m.group(2).strip() != t["prompt"].strip():
            if check_only:
                failures.append(f"{path.name} Section 7 与 templates.json 不同步")
            else:
                text = pattern.sub(lambda mm: mm.group(1) + t["prompt"] + mm.group(3), text, count=1)
                path.write_text(text, encoding="utf-8")


def run(check_only):
    templates = load_templates()
    failures = []

    # 1. index.html
    index = ROOT / "index.html"
    text = index.read_text(encoding="utf-8")
    new_text = replace_region(text, BEGIN_MARK, END_MARK, gen_index_region(templates))
    if check_only:
        if new_text != text:
            failures.append("index.html TEMPLATE DATA 区与 templates.json 不同步")
    else:
        index.write_text(new_text, encoding="utf-8")

    # 2. README.md
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    new_text = replace_region(text, README_BEGIN, README_END, gen_readme_table(templates))
    if check_only:
        if new_text != text:
            failures.append("README.md 速查表与 templates.json 不同步")
    else:
        readme.write_text(new_text, encoding="utf-8")

    # 3. skill/SKILL.md 标签矩阵
    skill = ROOT / "skill" / "SKILL.md"
    text = skill.read_text(encoding="utf-8")
    new_text = replace_region(text, MATRIX_BEGIN, MATRIX_END, gen_skill_matrix(templates))
    if check_only:
        if new_text != text:
            failures.append("SKILL.md 标签矩阵与 templates.json 不同步")
    else:
        skill.write_text(new_text, encoding="utf-8")

    # 4. 根目录模板 Section 7
    sync_root_md(templates, check_only, failures)

    return failures


def main():
    check_only = "--check" in sys.argv
    failures = run(check_only)
    if failures:
        print("❌ 不同步 / 校验失败：")
        for f in failures:
            print("  -", f)
        sys.exit(1)
    print("✅ 校验通过：所有派生内容已与 data/templates.json 同步" if check_only
          else "✅ 生成完成：index.html / README.md / SKILL.md / 根目录模板均已同步")


if __name__ == "__main__":
    main()
